\c gophermart;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login VARCHAR(200) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL
);

GRANT ALL PRIVILEGES ON TABLE users TO gopher;