// Code generated by MockGen. DO NOT EDIT.
// Source: gophermart/internal/app/repositories (interfaces: OrderRepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "gophermart/internal/app/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOrderRepositoryInterface is a mock of OrderRepositoryInterface interface.
type MockOrderRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryInterfaceMockRecorder
}

// MockOrderRepositoryInterfaceMockRecorder is the mock recorder for MockOrderRepositoryInterface.
type MockOrderRepositoryInterfaceMockRecorder struct {
	mock *MockOrderRepositoryInterface
}

// NewMockOrderRepositoryInterface creates a new mock instance.
func NewMockOrderRepositoryInterface(ctrl *gomock.Controller) *MockOrderRepositoryInterface {
	mock := &MockOrderRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepositoryInterface) EXPECT() *MockOrderRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetByOrderNumber mocks base method.
func (m *MockOrderRepositoryInterface) GetByOrderNumber(arg0 context.Context, arg1 int64) (*entities.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrderNumber", arg0, arg1)
	ret0, _ := ret[0].(*entities.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrderNumber indicates an expected call of GetByOrderNumber.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetByOrderNumber(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrderNumber", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetByOrderNumber), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockOrderRepositoryInterface) GetByUserID(arg0 context.Context, arg1 int) ([]entities.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]entities.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetByUserID), arg0, arg1)
}

// GetFreshOrders mocks base method.
func (m *MockOrderRepositoryInterface) GetFreshOrders(arg0 context.Context, arg1 int) ([]entities.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreshOrders", arg0, arg1)
	ret0, _ := ret[0].([]entities.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreshOrders indicates an expected call of GetFreshOrders.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetFreshOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreshOrders", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetFreshOrders), arg0, arg1)
}

// GetTotalAccrualByUserID mocks base method.
func (m *MockOrderRepositoryInterface) GetTotalAccrualByUserID(arg0 context.Context, arg1 int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAccrualByUserID", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAccrualByUserID indicates an expected call of GetTotalAccrualByUserID.
func (mr *MockOrderRepositoryInterfaceMockRecorder) GetTotalAccrualByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAccrualByUserID", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).GetTotalAccrualByUserID), arg0, arg1)
}

// Store mocks base method.
func (m *MockOrderRepositoryInterface) Store(arg0 context.Context, arg1 *entities.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOrderRepositoryInterfaceMockRecorder) Store(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).Store), arg0, arg1)
}

// UpdateOrder mocks base method.
func (m *MockOrderRepositoryInterface) UpdateOrder(arg0 context.Context, arg1 *entities.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockOrderRepositoryInterfaceMockRecorder) UpdateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockOrderRepositoryInterface)(nil).UpdateOrder), arg0, arg1)
}
