BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    login VARCHAR(200) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    balance FLOAT NULL
);

COMMIT;