// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/repositories/withdraw_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "gophermart/internal/app/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockWithdrawRepositoryInterface is a mock of WithdrawRepositoryInterface interface.
type MockWithdrawRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawRepositoryInterfaceMockRecorder
}

// MockWithdrawRepositoryInterfaceMockRecorder is the mock recorder for MockWithdrawRepositoryInterface.
type MockWithdrawRepositoryInterfaceMockRecorder struct {
	mock *MockWithdrawRepositoryInterface
}

// NewMockWithdrawRepositoryInterface creates a new mock instance.
func NewMockWithdrawRepositoryInterface(ctrl *gomock.Controller) *MockWithdrawRepositoryInterface {
	mock := &MockWithdrawRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockWithdrawRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawRepositoryInterface) EXPECT() *MockWithdrawRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockWithdrawRepositoryInterface) GetByUserID(ctx context.Context, userID int) ([]entities.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]entities.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockWithdrawRepositoryInterfaceMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockWithdrawRepositoryInterface)(nil).GetByUserID), ctx, userID)
}

// GetTotalWithdrawByUserID mocks base method.
func (m *MockWithdrawRepositoryInterface) GetTotalWithdrawByUserID(ctx context.Context, userID int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalWithdrawByUserID", ctx, userID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalWithdrawByUserID indicates an expected call of GetTotalWithdrawByUserID.
func (mr *MockWithdrawRepositoryInterfaceMockRecorder) GetTotalWithdrawByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalWithdrawByUserID", reflect.TypeOf((*MockWithdrawRepositoryInterface)(nil).GetTotalWithdrawByUserID), ctx, userID)
}

// Save mocks base method.
func (m *MockWithdrawRepositoryInterface) Save(ctx context.Context, tx pgx.Tx, withdraw entities.Withdraw) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tx, withdraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockWithdrawRepositoryInterfaceMockRecorder) Save(ctx, tx, withdraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWithdrawRepositoryInterface)(nil).Save), ctx, tx, withdraw)
}
